# Generated by Django 2.2 on 2022-02-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_auto_20220217_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.products')),
            ],
        ),
    ]
